services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3000" # Ajuste se necessário
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/app_db
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn start:dev # ou yarn start:prod, dependendo da fase
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
